export const produse = [
  {
    id: 1,
    nume: "Cafea boabe arabica",
    pret: 24.99,
    imagine: "produs1.jpg",
    descriere:
      "Cafea de calitate superioară, prăjită mediu, cu arome de ciocolată și alune.",
  },
  {
    id: 2,
    nume: "Ceai verde natural",
    pret: 12.5,
    imagine: "produs2.jpg",
    descriere: "Frunze proaspete, recoltate manual, bogate în antioxidanți.",
  },
  {
    id: 3,
    nume: "Ciocolată neagră 70%",
    pret: 9.75,
    imagine: "produs3.jpg",
    descriere: "Fără zahăr adăugat, cu gust intens și cremos.",
  },
  {
    id: 4,
    nume: "Miere de salcâm",
    pret: 18.2,
    imagine: "produs4.jpg",
    descriere: "Miere pură, recoltată din zone nepoluate.",
  },
  {
    id: 5,
    nume: "Nuci românești",
    pret: 15.0,
    imagine: "produs5.jpg",
    descriere: "Nuci proaspete, bogate în grăsimi sănătoase.",
  },
  {
    id: 6,
    nume: "Ulei de măsline extravirgin",
    pret: 32.4,
    imagine: "produs6.jpg",
    descriere: "Presat la rece, ideal pentru salate și gătit.",
  },
  {
    id: 7,
    nume: "Sare de mare fină",
    pret: 5.3,
    imagine: "produs7.jpg",
    descriere: "Fără aditivi, recoltată din ape curate.",
  },
  {
    id: 8,
    nume: "Orez integral",
    pret: 7.8,
    imagine: "produs8.jpg",
    descriere: "Bogat în fibre și minerale, pentru o dietă echilibrată.",
  },
  {
    id: 9,
    nume: "Făină integrală de grâu",
    pret: 6.5,
    imagine: "produs9.jpg",
    descriere: "Pentru pâine și prăjituri sănătoase.",
  },
  {
    id: 10,
    nume: "Zahăr din trestie nerafinat",
    pret: 8.9,
    imagine: "produs10.jpg",
    descriere: "Cu gust și proprietăți naturale.",
  },
  {
    id: 11,
    nume: "Gem de căpșuni",
    pret: 11.2,
    imagine: "produs11.jpg",
    descriere: "Fără conservanți, făcut din fructe proaspete.",
  },
  {
    id: 12,
    nume: "Sirop de zmeură",
    pret: 14.6,
    imagine: "produs12.jpg",
    descriere: "Ideal pentru băuturi sau deserturi.",
  },
  {
    id: 13,
    nume: "Biscuiți integrali",
    pret: 9.2,
    imagine: "produs13.jpg",
    descriere: "Cu semințe și cereale, crocanți și gustoși.",
  },
  {
    id: 14,
    nume: "Fulgi de ovăz",
    pret: 5.8,
    imagine: "produs14.jpg",
    descriere: "Pentru mic dejun sănătos și energizant.",
  },
  {
    id: 15,
    nume: "Semințe de floarea-soarelui",
    pret: 6.4,
    imagine: "produs15.jpg",
    descriere: "Prăjite ușor, bogate în vitamina E.",
  },
  {
    id: 16,
    nume: "Migdale crude",
    pret: 22.3,
    imagine: "produs16.jpg",
    descriere: "Sursă excelentă de proteine și calciu.",
  },
  {
    id: 17,
    nume: "Alune de pădure",
    pret: 21.7,
    imagine: "produs17.jpg",
    descriere: "Cu gust intens, ideale pentru gustare.",
  },
  {
    id: 18,
    nume: "Stafide aurii",
    pret: 13.9,
    imagine: "produs18.jpg",
    descriere: "Uscate natural, fără sulfiți.",
  },
  {
    id: 19,
    nume: "Prune uscate",
    pret: 16.5,
    imagine: "produs19.jpg",
    descriere: "Bune pentru digestie și energie.",
  },
  {
    id: 20,
    nume: "Semințe de in",
    pret: 7.2,
    imagine: "produs20.jpg",
    descriere: "Bogate în acizi grași Omega-3.",
  },
  {
    id: 21,
    nume: "Chimen măcinat",
    pret: 4.5,
    imagine: "produs21.jpg",
    descriere: "Condiment aromat pentru preparate culinare.",
  },
  {
    id: 22,
    nume: "Boia dulce",
    pret: 5.1,
    imagine: "produs22.jpg",
    descriere: "De calitate superioară, din ardei roșu.",
  },
  {
    id: 23,
    nume: "Busuioc uscat",
    pret: 3.9,
    imagine: "produs23.jpg",
    descriere: "Ideal pentru paste și sosuri.",
  },
  {
    id: 24,
    nume: "Rozmarin uscat",
    pret: 4.2,
    imagine: "produs24.jpg",
    descriere: "Pentru carne și preparate la cuptor.",
  },
  {
    id: 25,
    nume: "Mărar uscat",
    pret: 3.5,
    imagine: "produs25.jpg",
    descriere: "Condiment clasic pentru supe și salate.",
  },
];

